server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/expense_auth
    username: postgres
    password: your_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      INDENT_OUTPUT: true

jwt:
  secret: MySuperSecureSecretKeyThatIsAtLeast32Chars!
  expiration-ms: 86400000 # 1 day in milliseconds
